### ISSUE TITLE
add doc build and minimal install tests

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#253]
Just noticed this with the latest release, the current tests only check if all dependencies are installed but need to expand the test matrix to include minimal installs of fastplotlib with only `glfw` and not `jupyter_rfb`.

```python
(test-fpl) kushal@kushal-desktop:~
└─ $ ▶ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastplotlib.graphics import ImageGraphic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kushal/venvs/test-fpl/lib/python3.9/site-packages/fastplotlib/__init__.py", line 1, in <module>
    from .plot import Plot
  File "/home/kushal/venvs/test-fpl/lib/python3.9/site-packages/fastplotlib/plot.py", line 4, in <module>
    from .layouts._subplot import Subplot
  File "/home/kushal/venvs/test-fpl/lib/python3.9/site-packages/fastplotlib/layouts/__init__.py", line 1, in <module>
    from ._gridplot import GridPlot
  File "/home/kushal/venvs/test-fpl/lib/python3.9/site-packages/fastplotlib/layouts/_gridplot.py", line 12, in <module>
    from wgpu.gui.jupyter import JupyterWgpuCanvas
  File "/home/kushal/venvs/test-fpl/lib/python3.9/site-packages/wgpu/gui/jupyter.py", line 14, in <module>
    from jupyter_rfb import RemoteFrameBuffer
ModuleNotFoundError: No module named 'jupyter_rfb'
```

**Comment by kushalkolar** [comment]
This was done in #314
