### ISSUE TITLE
Look into WGPU max texture size limits

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#448]
And see if we can get rid of `HeatmapGraphic`

**Comment by kushalkolar** [comment]
So on Mac M2 it seems like the limit is 16384

```python
Device::create_texture error: Dimension X value 20000 exceeds the limit of 16384
Draw error
Traceback (most recent call last):
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/Users/ebalzani/Code/fastplotlib/fastplotlib/layouts/_figure.py", line 405, in render
    subplot.render()
  File "/Users/ebalzani/Code/fastplotlib/fastplotlib/layouts/_plot_area.py", line 366, in render
    self.viewport.render(self.scene, self.camera)
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/utils/viewport.py", line 78, in render
    self.renderer.render(scene, camera, rect=self.rect, flush=flush)
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/renderer.py", line 507, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 167, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 438, in update
    container.update(wobject, environment, env_hash, changed)
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 513, in update
    raise err
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 510, in update
    self.update_shader_data(wobject, changed)
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 545, in update_shader_data
    self.update_bind_groups()
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 640, in update_bind_groups
    binding_des, binding_layout_des = binding.get_bind_group_descriptors(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 278, in get_bind_group_descriptors
    "resource": ensure_wgpu_object(resource),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/update.py", line 184, in ensure_wgpu_object
    wgpu_texture = ensure_wgpu_object(resource.texture)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/pygfx/renderers/wgpu/engine/update.py", line 172, in ensure_wgpu_object
    resource._wgpu_object = device.create_texture(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_api.py", line 1013, in create_texture
    id = libf.wgpuDeviceCreateTexture(self._internal, struct)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 322, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
    In wgpuDeviceCreateTexture
    Dimension X value 20000 exceeds the limit of 16384
Present error
Traceback (most recent call last):
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/gui/base.py", line 138, in _draw_frame_and_present
    return self._canvas_context.present()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ebalzani/Code/dynamax/.venv/lib/python3.11/site-packages/wgpu/gui/offscreen.py", line 71, in present
    raise RuntimeError(msg)
RuntimeError: present() is called without a preceeding call to get_current_texture(). Note that present() is usually called automatically after the draw function returns.
```

**Comment by almarklein** [comment]
Also xref https://github.com/gfx-rs/wgpu-native/pull/379. To be honest I'm not really sure what the practical implications are for us (pygfx/fpl).

**Comment by kushalkolar** [comment]
Ah I didn't realize this was a bug in wgpu, because we did always get the 8192 several months ago, but recently we've been able to exceed it.

**Comment by almarklein** [comment]
The pr in wgpu-native has not landed in wgpu-py yet, btw. So something to look out for when we update wgpu-py.

**Comment by kushalkolar** [comment]
So I guess the heatmap tiling is here to stay, can close #449 ?

**Comment by almarklein** [comment]
I'd at least leave it until the next time we update wgpu-native in wgpu-py.
