### ISSUE TITLE
Axes disappear when going from perspective -> orthographic projection

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#572]
Playing with modifying FOV, this happens when going from FOV >=1 to FOV == 0

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/repos/wgpu-py/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/kushal/repos/wgpu-py/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/fastplotlib/fastplotlib/layouts/_imgui_figure.py", line 99, in render
    super().render(draw)
  File "/home/kushal/repos/fastplotlib/fastplotlib/layouts/_figure.py", line 398, in render
    subplot.render()
  File "/home/kushal/repos/fastplotlib/fastplotlib/layouts/_subplot.py", line 149, in render
    self.axes.update_using_camera()
  File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/_axes.py", line 528, in update_using_camera
    self.update(bbox, intersection)
  File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/_axes.py", line 565, in update
    statsx = self.x.update(
             ^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/objects/_ruler.py", line 221, in update
    self._update_sub_objects(visible_ticks, tick_auto_step)
  File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/_axes.py", line 212, in _update_sub_objects
    define_text(start_pos, f"")
  File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/_axes.py", line 202, in define_text
    ob.local.position = pos
    ^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 371, in position
    self.matrix = la.mat_compose(value, self.rotation, self.scale)
    ^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 594, in matrix
    self.flag_update()
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 580, in flag_update
    super().flag_update()
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 228, in flag_update
    callback(self)
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 83, in inner
    return self.callback_fn(weak_instance(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 725, in _own_updated
    self.flag_update()
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 708, in flag_update
    super().flag_update()
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 228, in flag_update
    callback(self)
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 83, in inner
    return self.callback_fn(weak_instance(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/objects/_base.py", line 188, in _update_uniform_buffers
    self.uniform_buffer.data["world_transform_inv"] = transform.inverse_matrix.T
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 277, in inverse_matrix
    return self._inverse_matrix
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 48, in __get__
    cache = (instance.last_modified, self.compute_fn(instance))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/utils/transform.py", line 161, in _inverse_matrix
    return mat_inv(self.matrix)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/fpl/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2022, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/fpl/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 1681, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/fpl/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 121, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
Draw error: SVD did not converge (2)
Draw error: SVD did not converge (3)
Draw error: SVD did not converge (4)
Draw error: SVD did not converge (5)
Draw error: SVD did not converge (6)
Draw error: SVD did not converge (7)
```

**Comment by kushalkolar** [comment]
So this is an issue with `np.linalg.pinv`. It does not ocurr in numpy v2 where pygfx uses `np.linalg.inv` instead.
