### ISSUE TITLE
Optional package imgui-bundle is now mandatory

### ISSUE THREAD

**Issue by jcafhe** [fastplotlib/fastplotlib#677]
Hi,

For the current version in development (main branch commit https://github.com/fastplotlib/fastplotlib/commit/f0f80c6a4deabb0941154584c854f2004b0cc316), when I run a script  just simple as below in a native python interpreter:

```python
import fastplotlib
```
I get a ModuleNotFoundError  'imgui_bundle':

```python
Traceback (most recent call last):
  File "***\minimal.py", line 1, in <module>
    import fastplotlib as fpl
  File "***\fastplotlib\__init__.py", line 19, in <module>
    from .widgets import ImageWidget
  File "***\fastplotlib\widgets\__init__.py", line 1, in <module>
    from .image_widget import ImageWidget
  File "***\fastplotlib\widgets\image_widget\__init__.py", line 1, in <module>
    from ._widget import ImageWidget
  File "***\fastplotlib\widgets\image_widget\_widget.py", line 12, in <module>
    from ._sliders import ImageWidgetSliders
  File "***\fastplotlib\widgets\image_widget\_sliders.py", line 4, in <module>
    from imgui_bundle import imgui, icons_fontawesome_6 as fa
ModuleNotFoundError: No module named 'imgui_bundle'
```
It seems that imgui is now mandatory even though it is declared as optional in the list of extra requires. Since 0.3 is under developement, do you intend to make imgui-bundle a required package?

**Comment by kushalkolar** [comment]
Thanks for posting! We'll fix this. We do not intend for imgui to be required.
